import Anthropic from '@anthropic-ai/sdk'
import type { BranchCommitInfo } from './git'
import type { CommitInfo, PolishEvent } from './types'

// ============================================================================
// Configuration
// ============================================================================

const DEFAULT_MODEL = 'anthropic/claude-3.5-sonnet'

function getAnthropicClient(): Anthropic {
  const apiKey = process.env.ANTHROPIC_AUTH_TOKEN || process.env.OPENROUTER_API_KEY
  const baseURL = process.env.ANTHROPIC_BASE_URL || 'https://openrouter.ai/api/v1'

  if (!apiKey) {
    throw new Error('ANTHROPIC_AUTH_TOKEN or OPENROUTER_API_KEY environment variable is required')
  }

  return new Anthropic({
    apiKey,
    baseURL
  })
}

// ============================================================================
// PR Summary Generation
// ============================================================================

export interface PRSummaryInput {
  commits: BranchCommitInfo[]
  mission?: string
  diffStats?: string
}

export interface PRSummary {
  title: string
  description: string
}

export async function generatePRSummary(input: PRSummaryInput): Promise<PRSummary> {
  const { commits, mission, diffStats } = input

  if (commits.length === 0) {
    return {
      title: 'Polish: Code quality improvements',
      description: '## Summary\n\nNo commits found.\n\n---\n_Generated by Polish with Claude_'
    }
  }

  // Build prompt for Claude
  const commitList = commits
    .map(c => `- ${c.message} (${c.hash})`)
    .join('\n')

  const prompt = `Tu es un expert en documentation de code. Génère un résumé de Pull Request clair et concis.

## Contexte
${mission ? `Mission originale: ${mission}\n\n` : ''}Commits effectués:
${commitList}

${diffStats ? `\nStatistiques des changements:\n${diffStats}\n` : ''}

## Ta tâche
Génère un résumé de PR au format suivant:

TITLE: [Un titre concis et descriptif en une ligne]

DESCRIPTION:
## Summary
[2-3 phrases décrivant ce qui a été fait et pourquoi]

## Changes
[Liste à puces des changements principaux, groupés par thème]

## Impact
[Impact sur le projet: performance, qualité du code, nouveautés, etc.]

---
_Generated by Polish with Claude_

## Règles
- Le titre doit être court (max 60 caractères)
- Utilise un français clair et professionnel
- Groupe les commits similaires ensemble
- Mets en avant les bénéfices pour le projet
- Sois factuel, pas de marketing`

  try {
    const client = getAnthropicClient()
    const response = await client.messages.create({
      model: DEFAULT_MODEL,
      max_tokens: 1000,
      messages: [
        {
          role: 'user',
          content: prompt
        }
      ]
    })

    const text = response.content[0].type === 'text' ? response.content[0].text : ''

    // Parse response
    const titleMatch = text.match(/TITLE:\s*(.+?)(?:\n|$)/i)
    const descMatch = text.match(/DESCRIPTION:\s*([\s\S]+)$/i)

    const title = titleMatch?.[1]?.trim() || 'Polish: Code quality improvements'
    const description = descMatch?.[1]?.trim() || `## Summary\n\nCode improvements applied.\n\n---\n_Generated by Polish with Claude_`

    return { title, description }

  } catch (error) {
    console.error('Failed to generate PR summary:', error)

    // Fallback to basic summary
    return {
      title: mission ? `Polish: ${mission.slice(0, 50)}` : 'Polish: Code quality improvements',
      description: `## Summary\n\nAutomated code quality improvements.\n\n## Changes\n\n${commitList}\n\n---\n_Generated by Polish with Claude_`
    }
  }
}

// ============================================================================
// Session Summary Generation
// ============================================================================

export interface SessionSummaryInput {
  mission?: string
  initialScore: number
  finalScore: number
  commits: CommitInfo[]
  duration: number
  iterations: number
  stoppedReason?: string
}

export interface SessionSummary {
  overview: string
  achievements: string[]
  metrics: string
  explanation: string
}

export async function generateSessionSummary(input: SessionSummaryInput): Promise<SessionSummary> {
  const {
    mission,
    initialScore,
    finalScore,
    commits,
    duration,
    iterations,
    stoppedReason
  } = input

  const scoreDelta = finalScore - initialScore
  const durationMin = Math.round(duration / 60000)

  // Build prompt
  const commitList = commits
    .map(c => `- ${c.message} (+${c.scoreDelta.toFixed(1)} pts)`)
    .join('\n')

  const prompt = `Tu es un expert en analyse de qualité de code. Génère un résumé détaillé de session Polish.

## Contexte de la session
${mission ? `Mission: ${mission}\n` : ''}Score initial: ${initialScore.toFixed(1)}/100
Score final: ${finalScore.toFixed(1)}/100
Amélioration: +${scoreDelta.toFixed(1)} points
Durée: ${durationMin} minutes
Itérations: ${iterations}
Raison d'arrêt: ${stoppedReason || 'unknown'}

## Commits effectués
${commitList || 'Aucun commit'}

## Ta tâche
Génère un résumé structuré de la session au format suivant:

OVERVIEW:
[2-3 phrases résumant ce qui a été accompli]

ACHIEVEMENTS:
- [Réalisation 1]
- [Réalisation 2]
- [Réalisation 3]

METRICS:
[Analyse des métriques: progression du score, nombre de fixes, efficacité]

EXPLANATION:
[Explication détaillée de ce qui a été fait et pourquoi c'est important.
Mentionne les patterns de problèmes trouvés et les solutions appliquées.
3-5 phrases.]

## Règles
- Sois précis et factuel
- Mets en avant les accomplissements
- Explique la valeur ajoutée
- Utilise un ton professionnel mais accessible`

  try {
    const client = getAnthropicClient()
    const response = await client.messages.create({
      model: DEFAULT_MODEL,
      max_tokens: 1500,
      messages: [
        {
          role: 'user',
          content: prompt
        }
      ]
    })

    const text = response.content[0].type === 'text' ? response.content[0].text : ''

    // Parse response
    const overviewMatch = text.match(/OVERVIEW:\s*([\s\S]+?)(?=\n\nACHIEVEMENTS:|\n\nMETRICS:|$)/i)
    const achievementsMatch = text.match(/ACHIEVEMENTS:\s*([\s\S]+?)(?=\n\nMETRICS:|\n\nEXPLANATION:|$)/i)
    const metricsMatch = text.match(/METRICS:\s*([\s\S]+?)(?=\n\nEXPLANATION:|$)/i)
    const explanationMatch = text.match(/EXPLANATION:\s*([\s\S]+)$/i)

    const overview = overviewMatch?.[1]?.trim() || `Session completed with ${commits.length} improvements.`
    const achievementsText = achievementsMatch?.[1]?.trim() || ''
    const achievements = achievementsText
      .split('\n')
      .filter(line => line.trim().startsWith('-'))
      .map(line => line.trim().replace(/^-\s*/, ''))
      .filter(Boolean)

    const metrics = metricsMatch?.[1]?.trim() || `Score improved from ${initialScore.toFixed(1)} to ${finalScore.toFixed(1)} (+${scoreDelta.toFixed(1)} points)`
    const explanation = explanationMatch?.[1]?.trim() || 'Code quality improvements were applied successfully.'

    return {
      overview,
      achievements,
      metrics,
      explanation
    }

  } catch (error) {
    console.error('Failed to generate session summary:', error)

    // Fallback to basic summary
    return {
      overview: `Polish session completed: ${commits.length} improvements in ${durationMin} minutes.`,
      achievements: [
        `Improved code quality score by ${scoreDelta.toFixed(1)} points`,
        `Applied ${commits.length} fixes across ${iterations} iterations`,
        `Session ${stoppedReason === 'max_score' ? 'achieved target score' : 'completed successfully'}`
      ],
      metrics: `Initial: ${initialScore.toFixed(1)}/100 → Final: ${finalScore.toFixed(1)}/100 (+${scoreDelta.toFixed(1)} points)`,
      explanation: mission
        ? `Implemented and polished the mission: ${mission}. Applied automated code quality improvements including type fixes, lint corrections, and test additions.`
        : 'Applied automated code quality improvements including type fixes, lint corrections, and test additions.'
    }
  }
}
