import Anthropic from '@anthropic-ai/sdk'
import type { BranchCommitInfo } from './git'
import type { CommitInfo, PolishEvent, Provider } from './types'
import { getDefaultProvider } from './provider-store'
import { createAnthropicClient, getDefaultModelForProvider, getProviderFromEnvironment } from './provider-runtime'

// ============================================================================
// Configuration
// ============================================================================

const DEFAULT_MODEL = 'anthropic/claude-3.5-sonnet'

function getAnthropicClientWithProvider(provider?: Provider): { client: Anthropic; model: string } {
  // If provider is specified, use it
  if (provider) {
    return {
      client: createAnthropicClient(provider),
      model: getDefaultModelForProvider(provider.type)
    }
  }

  // Try to get default provider from DB
  const defaultProvider = getDefaultProvider()
  if (defaultProvider) {
    return {
      client: createAnthropicClient(defaultProvider),
      model: getDefaultModelForProvider(defaultProvider.type)
    }
  }

  // Fall back to environment variables
  const envProvider = getProviderFromEnvironment()
  if (envProvider) {
    return {
      client: createAnthropicClient(envProvider),
      model: getDefaultModelForProvider(envProvider.type)
    }
  }

  throw new Error('No AI provider configured. Please add a provider or set ANTHROPIC_AUTH_TOKEN environment variable.')
}

// ============================================================================
// PR Summary Generation
// ============================================================================

export interface PRSummaryInput {
  commits: BranchCommitInfo[]
  mission?: string
  diffStats?: string
}

export interface PRSummary {
  title: string
  description: string
}

export async function generatePRSummary(input: PRSummaryInput, provider?: Provider): Promise<PRSummary> {
  const { commits, mission, diffStats } = input

  if (commits.length === 0) {
    return {
      title: 'Polish: Code quality improvements',
      description: '## Summary\n\nNo commits found.\n\n---\n_Generated by Polish with Claude_'
    }
  }

  // Build prompt for Claude
  const commitList = commits
    .map(c => `- ${c.message} (${c.hash})`)
    .join('\n')

  const prompt = `You are a code documentation expert. Generate a clear and concise Pull Request summary.

## Context
${mission ? `Original mission: ${mission}\n\n` : ''}Commits made:
${commitList}

${diffStats ? `\nChange statistics:\n${diffStats}\n` : ''}

## Your Task
Generate a PR summary in the following format:

TITLE: [A concise and descriptive one-line title]

DESCRIPTION:
## Summary
[2-3 sentences describing what was done and why]

## Changes
[Bulleted list of main changes, grouped by theme]

## Impact
[Impact on the project: performance, code quality, new features, etc.]

---
_Generated by Polish with Claude_

## Rules
- Title must be short (max 60 characters)
- Use clear and professional language
- Group similar commits together
- Highlight the benefits for the project
- Be factual, not marketing`

  try {
    const { client, model } = getAnthropicClientWithProvider(provider)
    const response = await client.messages.create({
      model,
      max_tokens: 1000,
      messages: [
        {
          role: 'user',
          content: prompt
        }
      ]
    })

    const text = response.content[0].type === 'text' ? response.content[0].text : ''

    // Parse response
    const titleMatch = text.match(/TITLE:\s*(.+?)(?:\n|$)/i)
    const descMatch = text.match(/DESCRIPTION:\s*([\s\S]+)$/i)

    const title = titleMatch?.[1]?.trim() || 'Polish: Code quality improvements'
    const description = descMatch?.[1]?.trim() || `## Summary\n\nCode improvements applied.\n\n---\n_Generated by Polish with Claude_`

    return { title, description }

  } catch (error) {
    console.error('Failed to generate PR summary:', error)

    // Fallback to basic summary
    return {
      title: mission ? `Polish: ${mission.slice(0, 50)}` : 'Polish: Code quality improvements',
      description: `## Summary\n\nAutomated code quality improvements.\n\n## Changes\n\n${commitList}\n\n---\n_Generated by Polish with Claude_`
    }
  }
}

// ============================================================================
// Session Summary Generation
// ============================================================================

export interface SessionSummaryInput {
  mission?: string
  initialScore: number
  finalScore: number
  commits: CommitInfo[]
  duration: number
  iterations: number
  stoppedReason?: string
}

export interface SessionSummary {
  overview: string
  achievements: string[]
  metrics: string
  explanation: string
}

export async function generateSessionSummary(input: SessionSummaryInput, provider?: Provider): Promise<SessionSummary> {
  const {
    mission,
    initialScore,
    finalScore,
    commits,
    duration,
    iterations,
    stoppedReason
  } = input

  const scoreDelta = finalScore - initialScore
  const durationMin = Math.round(duration / 60000)

  // Build prompt
  const commitList = commits
    .map(c => `- ${c.message} (+${c.scoreDelta.toFixed(1)} pts)`)
    .join('\n')

  const prompt = `You are a code quality analysis expert. Generate a detailed Polish session summary.

## Session Context
${mission ? `Mission: ${mission}\n` : ''}Initial score: ${initialScore.toFixed(1)}/100
Final score: ${finalScore.toFixed(1)}/100
Improvement: +${scoreDelta.toFixed(1)} points
Duration: ${durationMin} minutes
Iterations: ${iterations}
Stop reason: ${stoppedReason || 'unknown'}

## Commits Made
${commitList || 'No commits'}

## Your Task
Generate a structured session summary in the following format:

OVERVIEW:
[2-3 sentences summarizing what was accomplished]

ACHIEVEMENTS:
- [Achievement 1]
- [Achievement 2]
- [Achievement 3]

METRICS:
[Metrics analysis: score progression, number of fixes, efficiency]

EXPLANATION:
[Detailed explanation of what was done and why it matters.
Mention the problem patterns found and solutions applied.
3-5 sentences.]

## Rules
- Be precise and factual
- Highlight accomplishments
- Explain the added value
- Use a professional but accessible tone`

  try {
    const { client, model } = getAnthropicClientWithProvider(provider)
    const response = await client.messages.create({
      model,
      max_tokens: 1500,
      messages: [
        {
          role: 'user',
          content: prompt
        }
      ]
    })

    const text = response.content[0].type === 'text' ? response.content[0].text : ''

    // Parse response
    const overviewMatch = text.match(/OVERVIEW:\s*([\s\S]+?)(?=\n\nACHIEVEMENTS:|\n\nMETRICS:|$)/i)
    const achievementsMatch = text.match(/ACHIEVEMENTS:\s*([\s\S]+?)(?=\n\nMETRICS:|\n\nEXPLANATION:|$)/i)
    const metricsMatch = text.match(/METRICS:\s*([\s\S]+?)(?=\n\nEXPLANATION:|$)/i)
    const explanationMatch = text.match(/EXPLANATION:\s*([\s\S]+)$/i)

    const overview = overviewMatch?.[1]?.trim() || `Session completed with ${commits.length} improvements.`
    const achievementsText = achievementsMatch?.[1]?.trim() || ''
    const achievements = achievementsText
      .split('\n')
      .filter(line => line.trim().startsWith('-'))
      .map(line => line.trim().replace(/^-\s*/, ''))
      .filter(Boolean)

    const metrics = metricsMatch?.[1]?.trim() || `Score improved from ${initialScore.toFixed(1)} to ${finalScore.toFixed(1)} (+${scoreDelta.toFixed(1)} points)`
    const explanation = explanationMatch?.[1]?.trim() || 'Code quality improvements were applied successfully.'

    return {
      overview,
      achievements,
      metrics,
      explanation
    }

  } catch (error) {
    console.error('Failed to generate session summary:', error)

    // Fallback to basic summary
    return {
      overview: `Polish session completed: ${commits.length} improvements in ${durationMin} minutes.`,
      achievements: [
        `Improved code quality score by ${scoreDelta.toFixed(1)} points`,
        `Applied ${commits.length} fixes across ${iterations} iterations`,
        `Session ${stoppedReason === 'max_score' ? 'achieved target score' : 'completed successfully'}`
      ],
      metrics: `Initial: ${initialScore.toFixed(1)}/100 → Final: ${finalScore.toFixed(1)}/100 (+${scoreDelta.toFixed(1)} points)`,
      explanation: mission
        ? `Implemented and polished the mission: ${mission}. Applied automated code quality improvements including type fixes, lint corrections, and test additions.`
        : 'Applied automated code quality improvements including type fixes, lint corrections, and test additions.'
    }
  }
}
