import { describe, it, expect, vi, beforeEach } from 'vitest'
import { generatePRSummary, generateSessionSummary } from '../summary-generator'
import type { PRSummaryInput, SessionSummaryInput } from '../summary-generator'
import type { BranchCommitInfo } from '../git'
import type { CommitInfo } from '../types'

// Mock Anthropic SDK with proper constructor
const mockCreate = vi.fn()
vi.mock('@anthropic-ai/sdk', () => {
  return {
    default: class MockAnthropic {
      messages = {
        create: mockCreate
      }
    }
  }
})

beforeEach(() => {
  vi.clearAllMocks()
  mockCreate.mockReset()
  process.env.OPENROUTER_API_KEY = 'test-api-key'
})

describe('generatePRSummary', () => {
  it('should return default summary when no commits', async () => {
    const input: PRSummaryInput = {
      commits: []
    }

    const result = await generatePRSummary(input)

    expect(result.title).toBe('Polish: Code quality improvements')
    expect(result.description).toContain('No commits found')
  })

  it('should generate summary from API response', async () => {
    mockCreate.mockResolvedValue({
      content: [{
        type: 'text',
        text: `TITLE: Fix linting issues

DESCRIPTION:
## Summary
Fixed various linting issues in the codebase.

## Changes
- Fixed ESLint errors
- Updated type definitions

## Impact
Improved code quality and maintainability.

---
_Generated by Polish with Claude_`
      }]
    })

    const commits: BranchCommitInfo[] = [
      { hash: 'abc123', message: 'fix: lint errors', date: '2024-01-01' }
    ]

    const input: PRSummaryInput = {
      commits,
      mission: 'Improve code quality'
    }

    const result = await generatePRSummary(input)

    expect(result.title).toBe('Fix linting issues')
    expect(result.description).toContain('Fixed various linting issues')
    expect(mockCreate).toHaveBeenCalledWith(
      expect.objectContaining({
        model: 'anthropic/claude-3.5-sonnet',
        max_tokens: 1000
      })
    )
  })

  it('should parse title and description correctly', async () => {
    mockCreate.mockResolvedValue({
      content: [{
        type: 'text',
        text: 'TITLE: Test Title\n\nDESCRIPTION:\n## Summary\nTest description'
      }]
    })

    const commits: BranchCommitInfo[] = [
      { hash: 'abc123', message: 'test commit', date: '2024-01-01' }
    ]

    const result = await generatePRSummary({ commits })

    expect(result.title).toBe('Test Title')
    expect(result.description).toContain('Test description')
  })

  it('should fallback when API fails', async () => {
    mockCreate.mockRejectedValue(new Error('API Error'))

    const commits: BranchCommitInfo[] = [
      { hash: 'abc123', message: 'fix: something', date: '2024-01-01' },
      { hash: 'def456', message: 'feat: new feature', date: '2024-01-02' }
    ]

    const input: PRSummaryInput = {
      commits,
      mission: 'Test mission'
    }

    const result = await generatePRSummary(input)

    expect(result.title).toBe('Polish: Test mission')
    expect(result.description).toContain('fix: something')
    expect(result.description).toContain('feat: new feature')
  })

  it('should include mission in prompt when provided', async () => {
    mockCreate.mockResolvedValue({
      content: [{
        type: 'text',
        text: 'TITLE: Test\n\nDESCRIPTION:\nTest'
      }]
    })

    const commits: BranchCommitInfo[] = [
      { hash: 'abc123', message: 'test', date: '2024-01-01' }
    ]

    await generatePRSummary({
      commits,
      mission: 'Fix all bugs'
    })

    expect(mockCreate).toHaveBeenCalledWith(
      expect.objectContaining({
        messages: [
          expect.objectContaining({
            content: expect.stringContaining('Mission originale: Fix all bugs')
          })
        ]
      })
    )
  })

  it('should include diff stats when provided', async () => {
    mockCreate.mockResolvedValue({
      content: [{
        type: 'text',
        text: 'TITLE: Test\n\nDESCRIPTION:\nTest'
      }]
    })

    const commits: BranchCommitInfo[] = [
      { hash: 'abc123', message: 'test', date: '2024-01-01' }
    ]

    await generatePRSummary({
      commits,
      diffStats: '5 files changed, 100 insertions(+), 50 deletions(-)'
    })

    expect(mockCreate).toHaveBeenCalledWith(
      expect.objectContaining({
        messages: [
          expect.objectContaining({
            content: expect.stringContaining('5 files changed')
          })
        ]
      })
    )
  })
})

describe('generateSessionSummary', () => {
  it('should generate summary from API response', async () => {
    mockCreate.mockResolvedValue({
      content: [{
        type: 'text',
        text: `OVERVIEW:
Successfully improved code quality through multiple iterations.

ACHIEVEMENTS:
- Fixed 10 linting errors
- Improved type safety
- Added test coverage

METRICS:
Score improved from 60.0 to 80.0, a gain of +20.0 points in 3 iterations.

EXPLANATION:
The session focused on addressing code quality issues systematically.
Multiple linting errors were resolved, improving maintainability.
Type definitions were strengthened for better reliability.`
      }]
    })

    const commits: CommitInfo[] = [
      { hash: 'abc123', message: 'fix: lint errors', scoreDelta: 10 },
      { hash: 'def456', message: 'feat: add types', scoreDelta: 10 }
    ]

    const input: SessionSummaryInput = {
      mission: 'Improve quality',
      initialScore: 60,
      finalScore: 80,
      commits,
      duration: 120000, // 2 minutes
      iterations: 3,
      stoppedReason: 'max_score'
    }

    const result = await generateSessionSummary(input)

    expect(result.overview).toContain('improved code quality')
    expect(result.achievements).toHaveLength(3)
    expect(result.achievements[0]).toContain('10 linting errors')
    expect(result.metrics).toContain('60.0 to 80.0')
    expect(result.explanation).toContain('session focused')
  })

  it('should parse achievements as bullet list', async () => {
    mockCreate.mockResolvedValue({
      content: [{
        type: 'text',
        text: `OVERVIEW:
Test overview

ACHIEVEMENTS:
- Achievement 1
- Achievement 2
- Achievement 3

METRICS:
Test metrics

EXPLANATION:
Test explanation`
      }]
    })

    const commits: CommitInfo[] = [
      { hash: 'abc', message: 'test', scoreDelta: 5 }
    ]

    const input: SessionSummaryInput = {
      initialScore: 50,
      finalScore: 55,
      commits,
      duration: 60000,
      iterations: 1
    }

    const result = await generateSessionSummary(input)

    expect(result.achievements).toEqual([
      'Achievement 1',
      'Achievement 2',
      'Achievement 3'
    ])
  })

  it('should fallback when API fails', async () => {
    mockCreate.mockRejectedValue(new Error('API Error'))

    const commits: CommitInfo[] = [
      { hash: 'abc123', message: 'fix: something', scoreDelta: 5 }
    ]

    const input: SessionSummaryInput = {
      mission: 'Test mission',
      initialScore: 60,
      finalScore: 65,
      commits,
      duration: 120000,
      iterations: 2,
      stoppedReason: 'max_iterations'
    }

    const result = await generateSessionSummary(input)

    expect(result.overview).toContain('1 improvements')
    expect(result.achievements).toHaveLength(3)
    expect(result.metrics).toContain('60.0')
    expect(result.metrics).toContain('65.0')
    expect(result.explanation).toContain('Test mission')
  })

  it('should calculate duration in minutes', async () => {
    mockCreate.mockResolvedValue({
      content: [{
        type: 'text',
        text: 'OVERVIEW:\nTest\n\nACHIEVEMENTS:\n- Test\n\nMETRICS:\nTest\n\nEXPLANATION:\nTest'
      }]
    })

    const commits: CommitInfo[] = [
      { hash: 'abc', message: 'test', scoreDelta: 5 }
    ]

    await generateSessionSummary({
      initialScore: 50,
      finalScore: 55,
      commits,
      duration: 180000, // 3 minutes
      iterations: 1
    })

    expect(mockCreate).toHaveBeenCalledWith(
      expect.objectContaining({
        messages: [
          expect.objectContaining({
            content: expect.stringContaining('Durée: 3 minutes')
          })
        ]
      })
    )
  })

  it('should handle no commits', async () => {
    mockCreate.mockResolvedValue({
      content: [{
        type: 'text',
        text: 'OVERVIEW:\nNo changes\n\nACHIEVEMENTS:\n\nMETRICS:\nNo improvement\n\nEXPLANATION:\nNothing done'
      }]
    })

    const input: SessionSummaryInput = {
      initialScore: 80,
      finalScore: 80,
      commits: [],
      duration: 10000,
      iterations: 0
    }

    const result = await generateSessionSummary(input)

    expect(result.overview).toBeDefined()
    expect(mockCreate).toHaveBeenCalledWith(
      expect.objectContaining({
        messages: [
          expect.objectContaining({
            content: expect.stringContaining('Aucun commit')
          })
        ]
      })
    )
  })

  it('should use fallback when parsing fails', async () => {
    mockCreate.mockResolvedValue({
      content: [{
        type: 'text',
        text: 'Invalid response format'
      }]
    })

    const commits: CommitInfo[] = [
      { hash: 'abc', message: 'test', scoreDelta: 5 }
    ]

    const input: SessionSummaryInput = {
      initialScore: 50,
      finalScore: 55,
      commits,
      duration: 60000,
      iterations: 1
    }

    const result = await generateSessionSummary(input)

    // Should use default values when parsing fails
    expect(result.overview).toContain('1 improvements')
    expect(result.metrics).toContain('50.0')
    expect(result.explanation).toBeDefined()
  })
})
