import { NextRequest, NextResponse } from 'next/server'
import { push, createPR, getBranchCommits, getRemoteUrl } from '@/lib/git'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const {
      projectPath = process.cwd(),
      branchName,
      baseBranch = 'main',
      title,
      customDescription
    } = body

    if (!branchName) {
      return NextResponse.json(
        { error: 'branchName is required' },
        { status: 400 }
      )
    }

    // Get GitHub token from environment
    const token = process.env.GITHUB_TOKEN
    if (!token) {
      return NextResponse.json(
        { error: 'GITHUB_TOKEN environment variable is not set' },
        { status: 500 }
      )
    }

    // Get remote URL
    const remoteUrl = await getRemoteUrl(projectPath)
    if (!remoteUrl) {
      return NextResponse.json(
        { error: 'No remote origin found' },
        { status: 400 }
      )
    }

    // Get commits for description
    const commits = await getBranchCommits(projectPath, branchName, baseBranch)

    // Build PR description
    let description = `## Polish Improvements\n\n`
    description += `This PR contains automated code quality improvements made by Polish.\n\n`

    if (commits.length > 0) {
      description += `### Changes\n\n`
      for (const commit of commits) {
        description += `- ${commit.message} (\`${commit.hash}\`)\n`
      }
      description += '\n'
    }

    if (customDescription) {
      description += `### Additional Notes\n\n${customDescription}\n\n`
    }

    description += `---\n_Generated by [Polish](https://github.com/anthropics/polish)_`

    // Push the branch to remote
    await push(projectPath, branchName, token)

    // Create PR
    const prTitle = title || `Polish: Code quality improvements`
    const prUrl = await createPR(remoteUrl, branchName, prTitle, description, token)

    return NextResponse.json({
      success: true,
      prUrl,
      commits: commits.length
    })

  } catch (error) {
    console.error('Failed to create PR:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to create PR' },
      { status: 500 }
    )
  }
}
